name: just_testing

on:
  push:
    branches:
      - sluhtala
      - master

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test 
        run: echo 'test test test'
      - name: commit message
        env:
          CONTAINS: ${{ contains(join(github.event.commits.*.message), '#skip')}}
        run: echo "$CONTAINS"