name: just_testing

on:
  push:
    branches:
      - sluhtala
      - master

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test 
        run: echo 'test test test'
      - name: commit message
        env:
          COM_MSG: ${{ join(github.event.commits.*.message, ' ') }}
          CONTAINS: ${{ contains($COM_MSG, '#skip')}}
        run: echo "$CONTAINS"